20170313 release

diff --git a/debian/raspberrypi-sys-mods.postinst b/debian/raspberrypi-sys-mods.postinst
--- a/debian/raspberrypi-sys-mods.postinst
+++ b/debian/raspberrypi-sys-mods.postinst
@@ -56,6 +56,10 @@ case "${1}" in
       echo "Removing old NOPASSWD line, if present..."
       sed '/pi ALL=(ALL) NOPASSWD: ALL/d' -i /etc/sudoers || echo "Failed"
     fi
+    if dpkg --compare-versions "${2}" lt "20170313"; then
+      echo "Updating documentation URL in /boot/config.txt..."
+      sed -i 's|http://www.raspberrypi.org/documentation/configuration/config-txt.md|http://rpf.io/configtxtreadme|' /boot/config.txt || echo "Failed"
+    fi
     ;;
 
   abort-upgrade|abort-remove|abort-deconfigure)
