Add checks for 010_pi-nopasswd install

diff --git a/debian/raspberrypi-sys-mods.postinst b/debian/raspberrypi-sys-mods.postinst
--- a/debian/raspberrypi-sys-mods.postinst
+++ b/debian/raspberrypi-sys-mods.postinst
@@ -39,12 +39,17 @@ case "${1}" in
       echo "Adjusting cmdline.txt..."
       sed -e "s|=ttyAMA0|=serial0|;s|=ttyS0|=serial1|;" -i /boot/cmdline.txt || echo "Failed"
     fi
-    if dpkg --compare-versions "${2}" lt-nl "20160916"; then
-      echo "Removing old sysctl tweaks if present..."
+    if dpkg --compare-versions "${2}" lt "20160916"; then
+      echo "Removing old sysctl tweaks, if present..."
       sed -n '1h;1!H;${;g;s/\n\# rpi tweaks\nvm\.swappiness=1\nvm\.min_free_kbytes = 8192//g;p;}' -i /etc/sysctl.conf
     fi
-    if dpkg --compare-versions "${2}" lt "20161018"; then
-      echo "Removing old NOPASSWD line..."
+    if dpkg --compare-versions "${2}" lt-nl "20161018" && \
+       ! grep -Eq '^pi ALL=\(ALL\) NOPASSWD: ALL$' /etc/sudoers; then
+      echo "Old entry not found. Disabling new NOPASSWD line..."
+      sed -e '/^pi/ s/^#*/#/' -i /etc/sudoers.d/010_pi-nopasswd || echo "Failed"
+    fi
+    if dpkg --compare-versions "${2}" lt "20161018+3"; then
+      echo "Removing old NOPASSWD line, if present..."
       sed '/pi ALL=(ALL) NOPASSWD: ALL/d' -i /etc/sudoers || echo "Failed"
     fi
     ;;
