get_fw_loc: fix typo

diff --git a/usr/lib/raspberrypi-sys-mods/get_fw_loc b/usr/lib/raspberrypi-sys-mods/get_fw_loc
--- a/usr/lib/raspberrypi-sys-mods/get_fw_loc
+++ b/usr/lib/raspberrypi-sys-mods/get_fw_loc
@@ -15,7 +15,7 @@ if [ -z "$FWLOC" ]; then
     done
   fi
   if [ "$FWLOC" = "NOT_FOUND" ]; then
-    echo "WARNING: Firmware partition not found, searching for config.txt.."  >$2
+    echo "WARNING: Firmware partition not found, searching for config.txt.."  >&2
     for FWLOC in /boot/firmware /boot NOT_FOUND; do
       if [ -f "$FWLOC/config.txt" ]; then
         break
